### ISSUE TITLE
Test behaviors of the video player

### ISSUE THREAD

**Issue by sdercolin** [sdercolin/vlabeler#46]
Due to upgrade of compose, `LocalLayerContainer` is not accessiable anymore.
So I switched to SwingPanel.
https://github.com/sdercolin/vlabeler/commit/a6d466edf3c1890baec4a1f14fb032c4de6da085

@cyclekiller Could you take a look and have some tests with the video player?

**Comment by cyclekiller** [comment]
Hi, due to device change, I don't have the original dev environment on my computer now. I can test it but I'm not able to debug any errors currently.

**Comment by cyclekiller** [comment]
The "embedded video" doesn't work and shows the following error:
![image](https://github.com/user-attachments/assets/a0599e11-f015-4b6d-a18d-7027d977fabc)

The "new window" video works fine. I think we can delete the embedded video part, because it relies too much on the compose ui and is hard to maintain. People can still use this feature by opening videos in the new window.

**Comment by colin-weng-s** [comment]
Oh,,, okay... so let me force using "new window" for now and look into it more in the future!
