### ISSUE TITLE
Cannot use negative overlap

### ISSUE THREAD

**Issue by maeblythe** [sdercolin/vlabeler#7]
Negative overlap is mostly used when a plosive CV sample is cut too short. Negative overlap allows you to increase the length of the overlap so that the plosive will play correctly.

What I was trying to do was convert a VCV sample to a - C sample. It is possible to set overlap to zero and it work, but I usually set overlap to negative in this case to make it look like a normal - C sample.

**Comment by sdercolin** [comment]
Will add a labeler option named "UTAU oto labeler plus" which separates UTAU's "left/offset" from vLabeler's "start", so that Overlap can be moved to left side of "left".

Preview:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/7665216/176348948-8230c643-872e-4d5f-9d13-a28f7e491d21.png">

**Comment by sdercolin** [comment]
https://github.com/sdercolin/vlabeler/commit/8b8e8d21180dbc754ad907852dae60704497958e

**Comment by sdercolin** [comment]
Provided in the latest 1.0.0-alpha4 release
